# -*- coding: utf-8 -*-
"""Conteúdo das páginas do site da Especitá. Edite aqui e rode build_site.py.
Regras do CFO: sem preço, sem 'grátis', sem promessa de resultado, sem depoimento.
Nome + CRO em toda página (o template já coloca)."""

SITE = {
    "nome": "Especitá Odontologia e Estética",
    "nome_curto": "Especitá",
    "dominio": "https://clinicaespecita.com",  # domínio atual da clínica (WordPress na Hostinger); trocar se o endereço final for outro
    "cidade": "Brusque",
    "endereco": "Rua Sete de Setembro, 55 · Sala 1 · Santa Rita · Brusque/SC · 88352-000",
    "endereco_curto": "Rua Sete de Setembro, 55, Sala 1, Santa Rita, Brusque",
    "referencia": "em frente à ponte dos bombeiros",
    "whatsapp": "554797789519",
    "whatsapp_fmt": "(47) 99778-9519",
    "instagram": "https://www.instagram.com/clinicaespecita/",
    "instagram_handle": "@clinicaespecita",
    "maps": "https://www.google.com/maps/search/?api=1&query=Rua+Sete+de+Setembro+55+Santa+Rita+Brusque+SC",
    "horario": "Segunda a sexta, 8h às 18h · Sábado, 8h às 12h",
    "horario_schema": [
        {"@type": "OpeningHoursSpecification", "dayOfWeek": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], "opens": "08:00", "closes": "18:00"},
        {"@type": "OpeningHoursSpecification", "dayOfWeek": ["Saturday"], "opens": "08:00", "closes": "12:00"},
    ],
    "dra": "Dra. Catiucia L. Riffel",
    "cro": "CRO-SC 14067",
    "epao": "EPAO 4417 (habilitação em Harmonização Orofacial)",
    "geo": {"lat": -27.098, "lng": -48.918},  # aproximado; ajustar pelo Google Maps
}

NAV = [
    ("implante-dentario", "Implante"),
    ("ortodontia", "Ortodontia"),
    ("harmonizacao-facial", "Harmonização"),
    ("odontopediatria", "Infantil"),
    ("dentista-em-brusque", "Avaliação"),
]

# ------------------------------------------------------------------
# Cada serviço: slug, título SEO, h1, resumo, "para quem", "como é", FAQ, widget, cta
# ------------------------------------------------------------------
SERVICOS = [
dict(
    slug="dente-quebrado",
    grupo="Urgência",
    menu="Dente quebrado",
    title="Dente quebrado em Brusque: atendimento de urgência | Especitá",
    description="Quebrou ou lascou um dente? A Especitá reserva encaixes de urgência todos os dias em Brusque. Saiba o que fazer agora e fale com a recepção pelo WhatsApp.",
    h1="Dente quebrado? Encaixe de urgência em Brusque",
    lede="Um dente quebrado assusta, mas quase sempre tem solução no mesmo dia. A Especitá reserva horários de encaixe para urgências, de segunda a sábado, em frente à ponte dos bombeiros.",
    keywords=["dente quebrado", "dentista urgência Brusque", "dente lascado", "restauração de dente quebrado"],
    para_quem=[
        ("Quebrou ou lascou um dente da frente", "Impacto, mordida em algo duro ou dente já fragilizado por cárie ou restauração antiga."),
        ("Restauração ou pedaço do dente caiu", "O dente fica sensível e com a borda cortante; quanto antes for avaliado, mais simples o reparo."),
        ("Dente trincou e dói ao mastigar", "Trinca nem sempre aparece a olho nu. A avaliação define se é restauração, faceta ou tratamento de canal."),
    ],
    como=[
        ("Chame no WhatsApp e conte o que aconteceu", "Mande uma foto se puder. A recepção responde em poucos minutos no horário de atendimento e já oferece o encaixe do dia."),
        ("Avaliação com a Dra. Catiucia", "Exame, radiografia se necessário e explicação clara do que o dente precisa: restauração, faceta, coroa ou outro tratamento."),
        ("Resolver a urgência primeiro", "A prioridade é proteger o dente e tirar o desconforto. O planejamento do restante, quando houver, vem com calma."),
    ],
    sinais_titulo="O que fazer até chegar à clínica",
    sinais=[
        "Guarde o pedaço do dente, se encontrar, num potinho com leite ou soro fisiológico.",
        "Evite mastigar do lado afetado e alimentos muito quentes, frios ou duros.",
        "Não use cola, esmalte ou produtos caseiros para 'colar' o dente.",
        "Se houver sangramento, pressione uma gaze limpa no local por alguns minutos.",
        "Em caso de dor forte, procure atendimento no mesmo dia.",
    ],
    widget="checklist-urgencia",
    faq=[
        ("Dente quebrado é urgência odontológica?", "Sim, principalmente quando há dor, sensibilidade ao frio, borda cortante ou exposição da parte interna do dente. Quanto antes for avaliado, menor a chance de infecção e mais opções de tratamento existem."),
        ("Dá para consertar um dente quebrado no mesmo dia?", "Em muitos casos, sim. Restaurações em resina costumam ser feitas na mesma consulta. Casos com fratura maior podem precisar de faceta, coroa ou tratamento de canal, que a Dra. explica na avaliação."),
        ("Quebrei o dente e não está doendo. Preciso ir mesmo assim?", "Sim. A ausência de dor não significa que o dente está protegido. Fraturas sem dor podem evoluir para cárie, sensibilidade ou infecção."),
        ("A Especitá atende urgência no sábado?", "Sim, aos sábados pela manhã. Fora do horário, mande mensagem no WhatsApp: a recepção responde no primeiro horário do dia seguinte com o encaixe."),
        ("Quanto custa consertar um dente quebrado?", "O valor depende do tipo de reparo que o dente precisa. Na avaliação, a Dra. Catiucia mostra as opções e a recepção explica as formas de pagamento."),
    ],
    cta="Olá! Vim pelo site, quebrei um dente e preciso de encaixe de urgência.",
    cta_label="Pedir encaixe de urgência",
    relacionados=["dor-de-dente", "lente-de-contato-dental", "dentista-em-brusque"],
),
dict(
    slug="dor-de-dente",
    grupo="Urgência",
    menu="Dor de dente",
    title="Dor de dente em Brusque: dentista com encaixe no mesmo dia | Especitá",
    description="Dor de dente que não passa precisa de avaliação. A Especitá atende urgências em Brusque com encaixe no mesmo dia. Fale com a recepção pelo WhatsApp.",
    h1="Dor de dente não espera. Encaixe no mesmo dia em Brusque",
    lede="Dor de dente que não melhora com o tempo quase sempre tem uma causa que precisa de tratamento: cárie profunda, inflamação, infecção ou trinca. A Especitá reserva encaixes diários para isso.",
    keywords=["dor de dente", "dentista Brusque urgência", "dor de dente o que fazer", "dentista perto de mim Brusque"],
    para_quem=[
        ("Dor forte, contínua ou que acorda à noite", "Sinal de inflamação da polpa ou infecção. É o tipo de dor que não resolve sozinha."),
        ("Dor ao morder ou sensibilidade ao quente e frio", "Pode ser cárie, trinca, restauração alta ou retração da gengiva. A avaliação define a causa."),
        ("Inchaço no rosto, gosto ruim na boca ou febre", "Pode indicar abscesso. Nesse caso, procure atendimento no mesmo dia."),
    ],
    como=[
        ("Mensagem no WhatsApp com duas perguntas", "A recepção pergunta há quanto tempo dói e se há inchaço ou febre, para dar prioridade a quem precisa de atendimento imediato."),
        ("Primeiro a dor, depois o plano", "Na consulta de urgência a Dra. Catiucia identifica a causa, alivia a dor e explica o que o dente precisa."),
        ("Tratamento com calma", "Se for necessário tratamento de canal, restauração ou extração, o planejamento é feito com você, sem pressa."),
    ],
    sinais_titulo="Quando procurar o dentista hoje mesmo",
    sinais=[
        "Dor que não passa com o tempo ou piora à noite.",
        "Inchaço no rosto ou na gengiva, febre ou gosto ruim na boca.",
        "Dor forte ao morder ou ao tocar o dente.",
        "Dente escurecido depois de uma pancada.",
        "Sensibilidade intensa ao quente que demora a passar.",
    ],
    widget="triagem-dor",
    faq=[
        ("Dor de dente passa sozinha?", "Às vezes a dor diminui, mas a causa continua. Quando a dor 'some' de repente, pode significar que o nervo do dente foi comprometido, e a infecção pode avançar sem dor. A avaliação continua necessária."),
        ("Posso tomar remédio antes da consulta?", "Oriente-se com um profissional de saúde sobre medicação. A Dra. Catiucia avalia o caso na consulta e orienta o que fazer. Não use remédio diretamente no dente."),
        ("Dor de dente com inchaço é grave?", "Inchaço indica infecção e precisa de atendimento no mesmo dia. Avise a recepção pelo WhatsApp que há inchaço ou febre: esses casos têm prioridade."),
        ("A Especitá atende quem nunca foi paciente?", "Sim. A maior parte dos atendimentos de urgência é de pessoas que ainda não conheciam a clínica."),
        ("Vou precisar fazer canal?", "Só a avaliação responde. Muitas dores são resolvidas com restauração ou tratamento da gengiva. Quando o canal é necessário, a Dra. explica cada etapa."),
    ],
    cta="Olá! Vim pelo site, estou com dor de dente e preciso de atendimento.",
    cta_label="Pedir encaixe para dor de dente",
    relacionados=["dente-quebrado", "tratamento-odontologico", "dentista-em-brusque"],
),
dict(
    slug="implante-dentario",
    grupo="Implante e prótese",
    menu="Implante dentário",
    title="Implante dentário em Brusque: avaliação com planejamento digital | Especitá",
    description="Implante dentário e prótese protocolo em Brusque com a Dra. Catiucia (CRO-SC 14067). Entenda como funciona, para quem é indicado e agende sua avaliação pelo WhatsApp.",
    h1="Implante dentário em Brusque: voltar a mastigar e sorrir com segurança",
    lede="O implante substitui a raiz do dente perdido e recebe uma coroa fixa. Quando faltam muitos dentes, a prótese protocolo fixa sobre implantes devolve a mastigação sem a prótese móvel que solta ou machuca. Tudo começa com uma avaliação e um planejamento digital.",
    keywords=["implante dentário Brusque", "prótese protocolo", "implantes dentários", "dentista de implante Brusque"],
    para_quem=[
        ("Perdeu um ou mais dentes", "O implante evita que os dentes vizinhos se desloquem e que o osso da região se perca com o tempo."),
        ("Usa prótese móvel (dentadura) que solta ou machuca", "A prótese protocolo é fixa sobre implantes: não sai para comer nem para falar."),
        ("Tem dente condenado que precisa ser extraído", "Em alguns casos, extração e implante podem ser planejados em conjunto."),
    ],
    como=[
        ("Avaliação com planejamento digital", "Exame clínico, radiografia ou tomografia e planejamento do caso. A Dra. Catiucia mostra as opções, o número de implantes e o tipo de prótese indicado."),
        ("Cirurgia do implante", "Procedimento feito na clínica, com anestesia local. O tempo de cicatrização varia conforme o caso."),
        ("Prótese definitiva", "Coroa unitária ou prótese protocolo, feitas sob medida. Depois, manutenções periódicas garantem a durabilidade."),
    ],
    sinais_titulo="Sinais de que vale uma avaliação",
    sinais=[
        "Mastiga de um lado só por causa de um espaço sem dente.",
        "Prótese móvel com mais de 5 anos, que afrouxou ou machuca.",
        "Evita alguns alimentos ou restaurantes por insegurança com a prótese.",
        "Dentes vizinhos ao espaço começando a inclinar.",
        "Vergonha de sorrir por causa de um dente faltando.",
    ],
    widget="implante",
    faq=[
        ("Implante dentário dói?", "A cirurgia é feita com anestesia local e a maioria das pessoas relata desconforto leve nos primeiros dias, controlado com a medicação orientada pela Dra."),
        ("Quanto tempo leva um implante?", "Depende do caso. Da cirurgia à prótese definitiva, o processo costuma levar alguns meses, porque o implante precisa integrar ao osso. Em casos selecionados há protocolos mais rápidos, avaliados individualmente."),
        ("Qualquer pessoa pode fazer implante?", "A maioria sim. A avaliação verifica a quantidade de osso, a saúde da gengiva e condições gerais de saúde. Quando falta osso, existem técnicas de enxerto."),
        ("O que é prótese protocolo?", "É uma prótese fixa, apoiada em implantes, que substitui todos os dentes de uma arcada. Não sai da boca e devolve a mastigação e a fala com naturalidade."),
        ("Quanto custa um implante dentário em Brusque?", "O valor depende do número de implantes e do tipo de prótese. Na avaliação a Dra. Catiucia apresenta o plano completo, e a recepção explica as formas de pagamento."),
        ("Implante dura quanto tempo?", "Com higiene adequada e manutenções periódicas, implantes podem durar muitos anos. A durabilidade depende dos cuidados e do acompanhamento."),
    ],
    cta="Olá! Vim pelo site e quero agendar uma avaliação para implante dentário.",
    cta_label="Agendar avaliação de implante",
    relacionados=["tratamento-odontologico", "lente-de-contato-dental", "dentista-em-brusque"],
),
dict(
    slug="ortodontia",
    grupo="Ortodontia",
    menu="Aparelho ortodôntico",
    title="Ortodontia em Brusque: aparelho fixo e alinhador invisível | Especitá",
    description="Aparelho fixo ou alinhador invisível em Brusque. A Dra. Catiucia avalia o melhor caminho para crianças, adolescentes e adultos. Agende pelo WhatsApp.",
    h1="Ortodontia em Brusque: aparelho fixo ou alinhador, com acompanhamento perto de casa",
    lede="Dentes alinhados vão além da estética: melhoram a mastigação, a higiene e a saúde da gengiva. Na Especitá, a avaliação ortodôntica define se o caso pede aparelho fixo, alinhador invisível ou acompanhamento na infância.",
    keywords=["ortodontia Brusque", "aparelho ortodôntico Brusque", "ortodontista Brusque", "aparelho fixo"],
    para_quem=[
        ("Adolescentes e crianças", "A avaliação precoce identifica o melhor momento para começar. Nem todo caso precisa esperar todos os dentes permanentes."),
        ("Adultos que adiaram o aparelho", "Não existe idade limite. Alinhadores invisíveis são a escolha mais comum de quem trabalha com atendimento ao público."),
        ("Quem usou aparelho e os dentes voltaram a entortar", "Casos de recidiva costumam ser mais simples e rápidos de tratar."),
    ],
    como=[
        ("Avaliação ortodôntica", "Exame clínico, fotos e documentação. A Dra. explica o diagnóstico e as opções: fixo metálico, fixo estético ou alinhador."),
        ("Plano e tempo de tratamento", "Cada caso recebe um plano com duração estimada e frequência de manutenções, feitas aqui em Brusque."),
        ("Contenção", "Depois do tratamento, a contenção mantém o resultado. Faz parte do plano desde o início."),
    ],
    sinais_titulo="Quando procurar a avaliação",
    sinais=[
        "Dentes apinhados, separados ou girados.",
        "Mordida que não encaixa (cruzada, aberta ou profunda).",
        "Dificuldade para higienizar algumas regiões.",
        "Desgaste nos dentes ou dor na articulação.",
        "Criança que respira pela boca ou perdeu dentes de leite cedo.",
    ],
    widget="comparar-orto",
    faq=[
        ("Com que idade a criança deve fazer a primeira avaliação ortodôntica?", "Por volta dos 6 a 7 anos, quando os primeiros dentes permanentes aparecem. Muitas vezes nada precisa ser feito ainda, mas a avaliação permite planejar o momento certo."),
        ("Aparelho fixo ou alinhador: qual é melhor?", "Depende do caso e da rotina. O alinhador é discreto e removível; o fixo resolve alguns movimentos com mais previsibilidade. A Dra. Catiucia orienta na avaliação."),
        ("Quanto tempo dura o tratamento?", "Varia de alguns meses a mais de dois anos, conforme a complexidade. O plano apresentado na avaliação traz a estimativa do seu caso."),
        ("Aparelho dói?", "Há desconforto nos primeiros dias após colocar ou ajustar o aparelho, que passa rapidamente. Alinhadores costumam ser mais confortáveis."),
        ("Preciso fazer manutenção com que frequência?", "Em geral a cada 4 a 8 semanas, dependendo do tipo de aparelho. As manutenções são feitas na Especitá, em Brusque."),
    ],
    cta="Olá! Vim pelo site e quero agendar uma avaliação ortodôntica.",
    cta_label="Agendar avaliação ortodôntica",
    relacionados=["alinhador-invisivel", "odontopediatria", "clareamento-dental"],
),
dict(
    slug="alinhador-invisivel",
    grupo="Ortodontia",
    menu="Alinhador invisível",
    title="Alinhador invisível em Brusque: o aparelho que ninguém vê | Especitá",
    description="Alinhador invisível em Brusque com acompanhamento da Dra. Catiucia. Discreto, removível e planejado digitalmente. Avalie se o seu caso pode.",
    h1="Alinhador invisível em Brusque: alinhe os dentes sem metal",
    lede="O alinhador é uma sequência de placas transparentes, feitas sob medida, que movem os dentes aos poucos. Sai para comer e escovar, quase não aparece e o acompanhamento é feito aqui, em Brusque.",
    keywords=["alinhador invisível Brusque", "aparelho invisível", "alinhador transparente", "invisalign Brusque"],
    para_quem=[
        ("Adultos que trabalham com o público", "Reuniões, atendimento e fotos sem aparelho aparente."),
        ("Quem quer tirar o aparelho para comer e escovar", "A higiene fica mais simples e não há restrição de alimentos."),
        ("Casos leves a moderados de apinhamento ou espaços", "A avaliação com escaneamento digital mostra se o caso é indicado."),
    ],
    como=[
        ("Avaliação e escaneamento", "Fotos e registro digital dos dentes. A Dra. Catiucia analisa se o alinhador resolve o caso e estima a duração."),
        ("Planejamento digital", "O plano mostra o movimento previsto dos dentes e o número de placas."),
        ("Trocas e acompanhamento", "As placas são trocadas em intervalos definidos, com consultas de acompanhamento em Brusque."),
    ],
    sinais_titulo="O que o alinhador exige de você",
    sinais=[
        "Usar as placas cerca de 22 horas por dia.",
        "Tirar para comer e para escovar os dentes.",
        "Trocar a placa no dia indicado pelo plano.",
        "Comparecer às consultas de acompanhamento.",
        "Usar a contenção ao final do tratamento.",
    ],
    widget="comparar-orto",
    faq=[
        ("O alinhador invisível funciona para todos os casos?", "Resolve a maioria dos casos leves e moderados. Casos complexos podem precisar de aparelho fixo ou de uma combinação. A avaliação define."),
        ("O alinhador é realmente invisível?", "As placas são transparentes e ficam muito discretas. Quem olha de perto pode notar, mas em fotos e conversas normais quase ninguém percebe."),
        ("Posso comer com o alinhador?", "Não. As placas saem para comer e beber qualquer coisa além de água, e voltam depois da escovação."),
        ("Quanto tempo leva o tratamento com alinhador?", "Casos simples podem levar poucos meses; casos moderados, um ano ou mais. O planejamento digital traz a estimativa do seu caso."),
        ("Qual a diferença de preço entre alinhador e aparelho fixo?", "O valor depende do número de placas e da complexidade. Na avaliação a Dra. apresenta as opções, e a recepção explica as condições de pagamento."),
    ],
    cta="Olá! Vim pelo site e quero saber se meu caso pode usar alinhador invisível.",
    cta_label="Avaliar meu caso para alinhador",
    relacionados=["ortodontia", "clareamento-dental", "lente-de-contato-dental"],
),
dict(
    slug="odontopediatria",
    grupo="Infantil",
    menu="Dentista para crianças",
    title="Dentista infantil em Brusque: odontopediatria sem trauma | Especitá",
    description="Odontopediatria em Brusque: primeira visita de adaptação, prevenção e tratamento para bebês e crianças, com a Dra. Catiucia. Clube do Dente Corajoso.",
    h1="Dentista para crianças em Brusque: a primeira visita é só para conhecer",
    lede="Criança que conhece o dentista antes de sentir dor cresce sem medo. Na Especitá, a primeira consulta é uma visita de adaptação: a criança senta na cadeira, conhece o espelhinho e ganha o carimbo do Clube do Dente Corajoso. Sem procedimento, sem susto.",
    keywords=["dentista infantil Brusque", "odontopediatria Brusque", "dentista para bebê", "criança com medo de dentista"],
    para_quem=[
        ("Bebês a partir do primeiro dente", "A primeira visita é indicada até 1 ano de idade. Orientação de higiene, chupeta, mamadeira e alimentação."),
        ("Crianças que já tiveram uma experiência ruim", "A adaptação é feita no ritmo da criança, com linguagem lúdica e sem pressa."),
        ("Pais que querem prevenção", "Revisões a cada 6 meses, aplicação de flúor, selantes e acompanhamento do crescimento."),
    ],
    como=[
        ("Visita de adaptação", "A criança conhece a clínica, a cadeira e os instrumentos de forma lúdica. Os pais tiram dúvidas com a Dra. Catiucia."),
        ("Prevenção", "Limpeza, flúor, selantes e orientação de escovação adequada à idade."),
        ("Tratamento, quando necessário", "Feito em etapas curtas, com a criança participando e entendendo cada passo."),
    ],
    sinais_titulo="Dicas da Dra. para a primeira visita",
    sinais=[
        "Diga que vão 'conhecer a casa do dentista', sem usar as palavras 'não vai doer'.",
        "Evite contar experiências ruins que você teve no dentista.",
        "Traga a criança descansada e alimentada.",
        "Deixe que ela traga um brinquedo ou boneco favorito.",
        "Comemore depois da visita, independentemente de como foi.",
    ],
    widget="primeiro-dentinho",
    faq=[
        ("Com que idade levar o bebê ao dentista pela primeira vez?", "A recomendação das sociedades de odontopediatria é até o primeiro ano de vida, ou quando o primeiro dente nascer. Visitas precoces reduzem muito o risco de cárie nos primeiros anos."),
        ("Meu filho tem medo de dentista. Como funciona?", "A primeira consulta é apenas de adaptação, sem procedimento. A Dra. Catiucia mostra os instrumentos, deixa a criança explorar e marca o tratamento, se houver, para uma próxima visita, no ritmo dela."),
        ("Dente de leite precisa ser tratado se vai cair?", "Sim. Cárie em dente de leite causa dor, infecção e pode prejudicar o dente permanente que está se formando embaixo."),
        ("A partir de que idade a criança pode fazer avaliação ortodôntica?", "Por volta dos 6 a 7 anos. Muitas vezes é só acompanhamento, mas identifica cedo problemas de mordida e respiração."),
        ("Os pais entram na sala?", "Sim, principalmente nas primeiras visitas. Conforme a criança ganha confiança, a Dra. orienta o melhor formato."),
    ],
    cta="Olá! Vim pelo site e quero agendar a visita de adaptação do meu filho(a).",
    cta_label="Agendar visita de adaptação",
    relacionados=["ortodontia", "tratamento-odontologico", "dentista-em-brusque"],
),
dict(
    slug="tratamento-odontologico",
    grupo="Família",
    menu="Tratamento geral e família",
    title="Clínica odontológica em Brusque para toda a família | Especitá",
    description="Limpeza, restaurações, tratamento de gengiva, canal e revisões para toda a família em Brusque. Horários em sequência para pais e filhos. Especitá Odontologia.",
    h1="Um dentista para a família inteira, em Brusque",
    lede="Limpeza e revisão a cada 6 meses, restaurações, tratamento de gengiva, canal, extrações e acompanhamento das crianças. Na Especitá, a família pode ser atendida no mesmo dia, em horários seguidos, com a mesma profissional que conhece o histórico de cada um.",
    keywords=["clínica odontológica Brusque", "dentista em Brusque", "limpeza dental Brusque", "dentista família Brusque"],
    para_quem=[
        ("Famílias que querem um dentista fixo", "Histórico de todos no mesmo lugar, lembretes de revisão e horários em sequência."),
        ("Quem está há mais de um ano sem ir ao dentista", "A avaliação completa coloca a saúde bucal em dia, sem julgamento."),
        ("Quem precisa de tratamentos de rotina", "Restauração, limpeza, tratamento de gengiva, canal e extração, tudo na mesma clínica."),
    ],
    como=[
        ("Avaliação completa", "Exame clínico, fotos e radiografias quando necessário. Plano de tratamento explicado em linguagem simples."),
        ("Tratamento em etapas", "Prioridade para o que incomoda ou tem risco; o restante é organizado conforme a sua agenda."),
        ("Passaporte do Sorriso", "Revisões a cada 6 meses com lembrete pelo WhatsApp. Para as crianças, carimbo a cada visita."),
    ],
    sinais_titulo="O que fazemos na Especitá",
    sinais=[
        "Limpeza (profilaxia) e orientação de higiene.",
        "Restaurações estéticas em resina.",
        "Tratamento de gengiva (periodontia).",
        "Tratamento de canal (endodontia).",
        "Extrações, inclusive de sisos, com planejamento.",
        "Clareamento, lentes de contato e facetas.",
        "Implantes, próteses e ortodontia.",
        "Harmonização orofacial.",
    ],
    widget=None,
    faq=[
        ("A Especitá aceita convênio odontológico?", "Entre em contato pelo WhatsApp e informe o seu convênio. A recepção confirma as condições de atendimento."),
        ("De quanto em quanto tempo devo fazer limpeza?", "A cada 6 meses, em geral. Pessoas com problema de gengiva ou aparelho podem precisar de intervalos menores."),
        ("Dá para atender a família toda no mesmo dia?", "Sim. A recepção organiza horários em sequência para pais e filhos."),
        ("Vocês atendem urgência?", "Sim, com encaixes diários para dor de dente e dente quebrado."),
        ("Onde fica a clínica?", "Rua Sete de Setembro, 55, Sala 1, no bairro Santa Rita, em Brusque, em frente à ponte dos bombeiros. Há estacionamento próximo."),
    ],
    cta="Olá! Vim pelo site e quero agendar avaliação para a minha família.",
    cta_label="Agendar para a família",
    relacionados=["odontopediatria", "dentista-em-brusque", "clareamento-dental"],
),
dict(
    slug="harmonizacao-facial",
    grupo="Estética facial",
    menu="Harmonização facial",
    title="Harmonização orofacial em Brusque: botox e preenchimento com dentista habilitada | Especitá",
    description="Harmonização orofacial em Brusque com a Dra. Catiucia (CRO-SC 14067, habilitação EPAO 4417): toxina botulínica, preenchimento e bioestimulador com avaliação facial individual.",
    h1="Harmonização orofacial em Brusque: resultado discreto, avaliação individual",
    lede="A harmonização orofacial reúne procedimentos como toxina botulínica (botox), preenchimento com ácido hialurônico e bioestimulador de colágeno, sempre a partir de uma avaliação do rosto como um todo. Na Especitá, cada plano é individual e começa por uma conversa sobre o que você quer melhorar.",
    keywords=["harmonização facial Brusque", "botox Brusque", "preenchimento labial Brusque", "bioestimulador de colágeno Brusque"],
    para_quem=[
        ("Rugas de expressão (testa, entre as sobrancelhas, 'pés de galinha')", "A toxina botulínica relaxa a musculatura responsável pela ruga de expressão."),
        ("Volume e contorno (lábios, olheiras, sulcos)", "O preenchimento com ácido hialurônico repõe volume e suaviza sulcos."),
        ("Qualidade e firmeza da pele", "O bioestimulador de colágeno estimula a produção natural de colágeno ao longo dos meses."),
    ],
    como=[
        ("Avaliação facial", "Conversa sobre expectativas, análise das proporções do rosto e explicação do que cada procedimento faz e do que não faz."),
        ("Plano individual", "Regiões, produtos e etapas definidas para o seu caso, com termo de consentimento e orientações."),
        ("Procedimento e retorno", "Procedimentos rápidos, feitos na clínica. Retorno em cerca de 15 dias para avaliar e ajustar, quando indicado."),
    ],
    sinais_titulo="Perguntas que a Dra. faz na avaliação",
    sinais=[
        "O que te incomoda quando se olha no espelho?",
        "Já fez algum procedimento estético antes?",
        "Tem alguma data importante chegando?",
        "Alguma condição de saúde ou medicação em uso?",
        "Como você imagina o resultado?",
    ],
    widget="simulador-expressao",
    faq=[
        ("Dentista pode fazer botox e preenchimento?", "A cirurgiã-dentista com habilitação em Harmonização Orofacial atua na região orofacial. A Dra. Catiucia possui habilitação EPAO 4417. Em caso de dúvida sobre a regulamentação vigente, a clínica orienta na avaliação."),
        ("O resultado fica natural?", "A abordagem da Dra. prioriza doses e pontos que respeitam a expressão do rosto. O resultado depende de cada pessoa e é discutido com transparência na avaliação."),
        ("Quanto tempo dura o botox?", "O efeito da toxina botulínica costuma durar de 4 a 6 meses, variando entre pessoas. Preenchimentos e bioestimuladores têm durações diferentes, explicadas no plano."),
        ("Dói?", "Os procedimentos são rápidos e o desconforto é leve. Pode ser usado anestésico tópico em algumas regiões."),
        ("Quando devo fazer se tenho um evento?", "Para toxina botulínica, o ideal é fazer pelo menos 15 a 20 dias antes do evento. Preenchimentos também pedem um intervalo. Conte a data na avaliação."),
    ],
    cta="Olá! Vim pelo site e quero agendar uma avaliação facial.",
    cta_label="Agendar avaliação facial",
    relacionados=["clareamento-dental", "lente-de-contato-dental", "dentista-em-brusque"],
    aviso="Procedimentos estéticos de saúde exigem avaliação individual. Resultados variam de pessoa para pessoa. Esta página é informativa e não substitui a consulta.",
),
dict(
    slug="clareamento-dental",
    grupo="Estética do sorriso",
    menu="Clareamento dental",
    title="Clareamento dental em Brusque: personalizado e supervisionado | Especitá",
    description="Clareamento dental personalizado em Brusque, com moldeira sob medida e acompanhamento da Dra. Catiucia. Entenda a diferença para produtos de farmácia.",
    h1="Clareamento dental personalizado em Brusque",
    lede="Clareamento feito no consultório ou com moldeira sob medida para usar em casa, sempre com a concentração certa para o seu esmalte e acompanhamento profissional. Resultado uniforme e cuidado com a sensibilidade.",
    keywords=["clareamento dental Brusque", "clareamento dentista Brusque", "clarear os dentes", "clareamento para casamento"],
    para_quem=[
        ("Dentes amarelados por café, chá, vinho ou cigarro", "Manchas superficiais respondem bem ao clareamento supervisionado."),
        ("Casamento, formatura ou evento", "Planeje com antecedência: o protocolo leva algumas semanas para o resultado completo."),
        ("Quem já tentou produtos de farmácia sem resultado", "A diferença está na concentração, no ajuste da moldeira e no acompanhamento."),
    ],
    como=[
        ("Avaliação e limpeza", "Antes de clarear, a Dra. verifica cáries, restaurações e sensibilidade. A limpeza prévia melhora o resultado."),
        ("Protocolo personalizado", "No consultório, em casa com moldeira sob medida, ou combinado. Tom inicial registrado para comparação."),
        ("Acompanhamento", "Orientações sobre alimentação e sensibilidade durante o tratamento, e retorno para avaliar o resultado."),
    ],
    sinais_titulo="Cuidados durante o clareamento",
    sinais=[
        "Evite alimentos e bebidas com corante forte nos dias de aplicação.",
        "Use creme dental para sensibilidade, se orientado.",
        "Não aumente o tempo de uso da moldeira por conta própria.",
        "Restaurações e facetas não clareiam: a Dra. avalia se precisam ser trocadas depois.",
        "Mantenha a limpeza semestral para prolongar o resultado.",
    ],
    widget="escala-clareamento",
    faq=[
        ("Clareamento estraga o dente?", "Feito com supervisão e na concentração adequada, não. O que causa dano é o uso sem orientação, em excesso ou com produtos inadequados."),
        ("Quanto tempo dura o resultado?", "Em geral de 1 a 3 anos, dependendo dos hábitos. Retoques periódicos mantêm o tom."),
        ("Clareamento causa sensibilidade?", "Pode causar sensibilidade temporária. O protocolo personalizado e o uso de produtos dessensibilizantes reduzem bastante esse efeito."),
        ("Posso clarear com aparelho?", "Com aparelho fixo, o ideal é esperar a remoção. Com alinhador, em alguns casos é possível usar as próprias placas; a Dra. orienta."),
        ("Quanto tempo antes do casamento devo começar?", "Idealmente de 1 a 2 meses antes, para concluir o protocolo e fazer o retorno com calma."),
    ],
    cta="Olá! Vim pelo site e quero saber sobre clareamento dental.",
    cta_label="Agendar avaliação para clareamento",
    relacionados=["lente-de-contato-dental", "harmonizacao-facial", "alinhador-invisivel"],
),
dict(
    slug="lente-de-contato-dental",
    grupo="Estética do sorriso",
    menu="Lente de contato dental",
    title="Lente de contato dental em Brusque: facetas ultrafinas | Especitá",
    description="Lentes de contato dentais e facetas em Brusque com planejamento digital do sorriso pela Dra. Catiucia. Para dentes pequenos, espaçados, manchados ou desgastados.",
    h1="Lente de contato dental em Brusque: o sorriso planejado",
    lede="Lentes de contato dentais são lâminas finíssimas de porcelana ou resina, coladas sobre os dentes da frente para corrigir formato, cor, pequenos espaços e desgastes. O planejamento digital mostra a proposta antes de qualquer procedimento.",
    keywords=["lente de contato dental Brusque", "faceta dental Brusque", "lentes de contato dentais", "faceta de porcelana"],
    para_quem=[
        ("Dentes pequenos, curtos ou com espaços", "As lentes ajustam proporção e fecham pequenos espaços sem aparelho."),
        ("Manchas que o clareamento não resolve", "Manchas profundas ou de restaurações antigas podem ser cobertas pelas lentes."),
        ("Desgastes e pequenas fraturas nas bordas", "As lentes devolvem o comprimento e o contorno dos dentes."),
    ],
    como=[
        ("Avaliação e planejamento digital", "Fotos, análise do sorriso e simulação do resultado proposto. A Dra. explica se o caso pede lente, faceta ou outro tratamento."),
        ("Preparo mínimo e moldagem", "Lentes exigem desgaste mínimo ou nenhum. As peças são feitas sob medida em laboratório."),
        ("Cimentação e ajustes", "As lentes são coladas e ajustadas na oclusão. Orientações de cuidado e retorno."),
    ],
    sinais_titulo="O que avaliar antes de decidir",
    sinais=[
        "Saúde da gengiva e ausência de cáries ativas.",
        "Hábito de ranger os dentes (pode exigir placa de proteção).",
        "Expectativa de cor: as lentes podem ser mais claras que o clareamento alcança.",
        "Número de dentes envolvidos para um resultado harmônico.",
        "Manutenção: limpezas regulares e cuidado ao morder alimentos muito duros.",
    ],
    widget=None,
    faq=[
        ("Lente de contato dental e faceta são a mesma coisa?", "São parecidas. A lente é mais fina e exige menos desgaste do dente; a faceta é um pouco mais espessa e indicada quando há mais correção a fazer. A avaliação define."),
        ("As lentes duram quanto tempo?", "Lentes de porcelana, com bons cuidados, costumam durar muitos anos. Resina tem durabilidade menor e custo mais baixo."),
        ("Precisa desgastar o dente?", "Em muitos casos o desgaste é mínimo ou nenhum. Depende do posicionamento e do formato dos dentes."),
        ("Dá para fazer em um dente só?", "Sim, quando um dente está diferente dos outros. Para mudar a cor do sorriso inteiro, normalmente são feitos vários dentes."),
        ("Quanto custa lente de contato dental?", "O valor depende do material e do número de dentes. Na avaliação a Dra. Catiucia apresenta o planejamento, e a recepção explica as condições."),
    ],
    cta="Olá! Vim pelo site e quero agendar avaliação para lentes de contato dentais.",
    cta_label="Agendar avaliação do sorriso",
    relacionados=["clareamento-dental", "harmonizacao-facial", "implante-dentario"],
),
dict(
    slug="dentista-em-brusque",
    grupo="Avaliação",
    menu="Avaliação e check-up",
    title="Dentista em Brusque: avaliação completa na Especitá | Santa Rita",
    description="Procurando dentista em Brusque? A Especitá fica no Santa Rita, em frente à ponte dos bombeiros. Avaliação completa com a Dra. Catiucia, há mais de 10 anos na cidade.",
    h1="Dentista em Brusque: avaliação completa para começar do jeito certo",
    lede="Mudou para Brusque, está há tempo sem ir ao dentista ou quer uma segunda opinião? A avaliação completa na Especitá mostra como está a sua saúde bucal e organiza o que precisa ser feito, sem pressa e sem julgamento.",
    keywords=["dentista em Brusque", "dentista Brusque", "clínica odontológica Brusque Santa Rita", "check-up dentista"],
    para_quem=[
        ("Quem chegou agora em Brusque", "Uma clínica perto do centro, com estacionamento e atendimento pelo WhatsApp."),
        ("Quem está há mais de um ano sem dentista", "A avaliação completa identifica cáries iniciais, gengiva e desgastes antes que virem dor."),
        ("Quem quer uma segunda opinião", "Traga seus exames e orçamentos. A Dra. explica o que vê e o que recomenda."),
    ],
    como=[
        ("Conversa e histórico", "O que te trouxe, o que incomoda, hábitos e tratamentos anteriores."),
        ("Exame completo", "Dentes, gengiva, mordida, articulação e tecidos da boca. Fotos e radiografias quando necessário."),
        ("Plano em linguagem simples", "O que é urgente, o que pode esperar e as opções para cada item. Você decide com informação."),
    ],
    sinais_titulo="Por que a Especitá",
    sinais=[
        "Dra. Catiucia L. Riffel, CRO-SC 14067, há mais de 10 anos atendendo em Brusque.",
        "Odontologia geral, implantes, ortodontia, odontopediatria e harmonização no mesmo lugar.",
        "Atendimento pelo WhatsApp com resposta rápida e horários em sequência para a família.",
        "Rua Sete de Setembro, 55, Santa Rita, em frente à ponte dos bombeiros.",
        "Encaixes diários para urgência.",
    ],
    widget=None,
    faq=[
        ("Como marcar uma consulta na Especitá?", "Pelo WhatsApp (47) 99778-9519. A recepção responde no horário de atendimento e oferece os horários disponíveis."),
        ("A clínica fica em que bairro de Brusque?", "No Santa Rita, na Rua Sete de Setembro, 55, Sala 1, em frente à ponte dos bombeiros."),
        ("Preciso de encaminhamento?", "Não. Basta entrar em contato e agendar a avaliação."),
        ("Quanto tempo dura a avaliação?", "Cerca de 40 minutos, incluindo fotos e radiografias quando necessário."),
        ("Atendem no sábado?", "Sim, pela manhã, das 8h às 12h."),
    ],
    cta="Olá! Vim pelo site e quero agendar uma avaliação completa.",
    cta_label="Agendar avaliação completa",
    relacionados=["tratamento-odontologico", "implante-dentario", "odontopediatria"],
),
]

HOME = dict(
    title="Especitá Odontologia e Estética · Dentista em Brusque",
    description="Clínica odontológica em Brusque: implantes, ortodontia, odontopediatria, clareamento, lentes e harmonização orofacial com a Dra. Catiucia (CRO-SC 14067). Atendimento pelo WhatsApp.",
    h1="Odontologia e estética para a sua família, em Brusque",
    lede="Implantes, aparelhos, dentista para crianças, clareamento e harmonização orofacial no mesmo lugar, com a mesma profissional que conhece o seu histórico. Em frente à ponte dos bombeiros, no Santa Rita.",
    destaques=[
        ("10+", "anos atendendo famílias de Brusque"),
        ("1", "profissional que acompanha todo o seu tratamento"),
        ("6", "dias por semana com encaixe para urgência"),
    ],
    cta="Olá! Vim pelo site e quero agendar uma avaliação.",
)

SOBRE = dict(
    title="Dra. Catiucia L. Riffel · CRO-SC 14067 | Especitá Brusque",
    description="Conheça a Dra. Catiucia L. Riffel, cirurgiã-dentista responsável pela Especitá Odontologia e Estética, em Brusque, com habilitação em Harmonização Orofacial.",
    h1="Dra. Catiucia L. Riffel",
    texto=[
        "Cirurgiã-dentista registrada no CRO-SC sob o número 14067, a Dra. Catiucia atende em Brusque há mais de dez anos. Fundou a Especitá com uma ideia simples: a mesma profissional acompanha o paciente do primeiro contato até a manutenção, em qualquer especialidade.",
        "Possui habilitação em Harmonização Orofacial (EPAO 4417) e atua em odontologia geral, implantodontia, ortodontia, odontopediatria e estética do sorriso.",
        "A clínica fica na Rua Sete de Setembro, 55, no bairro Santa Rita, em frente à ponte dos bombeiros, com estacionamento próximo e atendimento de segunda a sábado.",
    ],
    formacao_placeholder="[Formação, cursos e especializações da Dra.: preencher com os dados oficiais]",
)
